# Generated by Django 4.1 on 2023-06-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldboss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_name', models.CharField(max_length=100)),
                ('est_datetime', models.DateTimeField()),
                ('min_datetime', models.DateTimeField()),
                ('max_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
