# Generated by Django 4.1 on 2023-06-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldboss', '0002_estimated'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('thumbs_up', models.PositiveIntegerField(default=0)),
                ('thumbs_down', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
